In [1]:
# Dataset : https://www.kaggle.com/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [2]:
import pandas as pd
import numpy as np
import re
import nltk
#nltk.download('popular')
#nltk.download('punkt')
#nltk.download('punkt_tab')
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv(r"C:\Users\Prathamesh\Downloads\Projects\Movie Recommendation System\movies rec\imdb_top_1000.csv")

## EDA

In [4]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [5]:
df['Poster_Link'][0]

'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg'

In [6]:
df.drop(columns=["Poster_Link", "Gross"], inplace=True)

In [7]:
df["actors"] = df[['Star1', 'Star2', 'Star3', 'Star4']].apply(lambda x: ', '.join(x.dropna()), axis=1)
df.drop(columns=['Star1', 'Star2', 'Star3', 'Star4'], inplace=True)

In [8]:
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,No_of_Votes,actors
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,2343110,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi..."
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,1620367,"Marlon Brando, Al Pacino, James Caan, Diane Ke..."
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,2303232,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,1129952,"Al Pacino, Robert De Niro, Robert Duvall, Dian..."
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,689845,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ..."

In [9]:
df.columns

Index(['Series_Title', 'Released_Year', 'Certificate', 'Runtime', 'Genre',
       'IMDB_Rating', 'Overview', 'Meta_score', 'Director', 'No_of_Votes',
       'actors'],
      dtype='object')

In [10]:
df['Series_Title'].nunique()

999

In [11]:
df.isnull().sum()

Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
No_of_Votes        0
actors             0
dtype: int64

In [12]:
df["Certificate"] = df["Certificate"].fillna(df["Certificate"].mode()[0])
df["Meta_score"] = df["Meta_score"].fillna(df["Meta_score"].mode()[0])

In [13]:
df.head(0)

Empty DataFrame
Columns: [Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Overview, Meta_score, Director, No_of_Votes, actors]
Index: []

In [14]:
cols = ["Series_Title", "Genre", "Director", "actors", "Overview"]

In [15]:
df1 = df[cols]
df1.head()

,Series_Title,Genre,Director,actors,Overview
0,The Shawshank Redemption,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",An organized crime dynasty's aging patriarch t...
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...",The early life and career of Vito Corleone in ...
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",A jury holdout attempts to prevent a miscarria...

## Text Preprocessing

In [16]:
# Text Lowercase:
df1['clean_overview'] = df1['Overview'].str.lower()
df1.head()

,Series_Title,Genre,Director,actors,Overview,clean_overview
0,The Shawshank Redemption,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",An organized crime dynasty's aging patriarch t...,an organized crime dynasty's aging patriarch t...
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,when the menace known as the joker wreaks havo...
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...",The early life and career of Vito Corleone in ...,the early life and career of vito corleone in ...
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",A jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...

In [17]:
# Removing numbers and punctuations
df1["clean_overview1"] = df1['clean_overview'].apply(lambda x: re.sub('[^a-zA-Z]',' ',x))
df1.head()

,Series_Title,Genre,Director,actors,Overview,clean_overview,clean_overview1
0,The Shawshank Redemption,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",An organized crime dynasty's aging patriarch t...,an organized crime dynasty's aging patriarch t...,an organized crime dynasty s aging patriarch t...
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...",The early life and career of Vito Corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",A jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...

In [18]:
# Removing unwanted space:

df1["clean_overview2"] = df1["clean_overview1"].apply(lambda x: re.sub('\s+', ' ',x))
df1.head()

,Series_Title,Genre,Director,actors,Overview,clean_overview,clean_overview1,clean_overview2
0,The Shawshank Redemption,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",An organized crime dynasty's aging patriarch t...,an organized crime dynasty's aging patriarch t...,an organized crime dynasty s aging patriarch t...,an organized crime dynasty s aging patriarch t...
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...",The early life and career of Vito Corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",A jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...

In [19]:
# Tokanization

In [20]:
df1['Tokenize'] = df1['clean_overview2'].apply(lambda x: nltk.word_tokenize(x))
df1.head()

,Series_Title,Genre,Director,actors,Overview,clean_overview,clean_overview1,clean_overview2,Tokenize
0,The Shawshank Redemption,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,"[two, imprisoned, men, bond, over, a, number, ..."
1,The Godfather,"Crime, Drama",Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...",An organized crime dynasty's aging patriarch t...,an organized crime dynasty's aging patriarch t...,an organized crime dynasty s aging patriarch t...,an organized crime dynasty s aging patriarch t...,"[an, organized, crime, dynasty, s, aging, patr..."
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,"[when, the, menace, known, as, the, joker, wre..."
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...",The early life and career of Vito Corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,"[the, early, life, and, career, of, vito, corl..."
4,12 Angry Men,"Crime, Drama",Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...",A jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,"[a, jury, holdout, attempts, to, prevent, a, m..."

In [21]:
stop_words = nltk.corpus.stopwords.words('english')
Word_List = []
for sentence in df1["Tokenize"]:
    temp = []
    for word in sentence:
        if word not in stop_words and len(word) >= 3:
            temp.append(word)
    Word_List.append(temp)

In [22]:
df1['Clean_Tokenize'] = Word_List

In [23]:
df1['Clean_Tokenize']

0      [two, imprisoned, men, bond, number, years, fi...
1      [organized, crime, dynasty, aging, patriarch, ...
2      [menace, known, joker, wreaks, havoc, chaos, p...
3      [early, life, career, vito, corleone, new, yor...
4      [jury, holdout, attempts, prevent, miscarriage...
                             ...
995    [young, new, york, socialite, becomes, interes...
996    [sprawling, epic, covering, life, texas, cattl...
997    [hawaii, private, cruelly, punished, boxing, u...
998    [several, survivors, torpedoed, merchant, ship...
999    [man, london, tries, help, counter, espionage,...
Name: Clean_Tokenize, Length: 1000, dtype: object

In [24]:
# Combining the words in Genre/Actors and Director columns into single words:
df1['Genre'] = df1['Genre'].apply(lambda x: x.split(','))
df1["actors"] = df1["actors"].apply(lambda x: x.split(',')[:4])
df1["Director"] = df1["Director"].apply(lambda x: x.split(','))

In [25]:
def clean_text(sentence):
    temp = []
    for word in sentence:
        temp.append(word.lower().replace(' ', ''))
    return temp

In [26]:
df1["Genre"] = [clean_text(x) for x in df1['Genre']]
df1["actors"] = [clean_text(x) for x in df1['actors']]
df1["Director"] = [clean_text(x) for x in df1['Director']]

In [27]:
df1.head()

,Series_Title,Genre,Director,actors,Overview,clean_overview,clean_overview1,clean_overview2,Tokenize,Clean_Tokenize
0,The Shawshank Redemption,[drama],[frankdarabont],"[timrobbins, morganfreeman, bobgunton, william...",Two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,"[two, imprisoned, men, bond, over, a, number, ...","[two, imprisoned, men, bond, number, years, fi..."
1,The Godfather,"[crime, drama]",[francisfordcoppola],"[marlonbrando, alpacino, jamescaan, dianekeaton]",An organized crime dynasty's aging patriarch t...,an organized crime dynasty's aging patriarch t...,an organized crime dynasty s aging patriarch t...,an organized crime dynasty s aging patriarch t...,"[an, organized, crime, dynasty, s, aging, patr...","[organized, crime, dynasty, aging, patriarch, ..."
2,The Dark Knight,"[action, crime, drama]",[christophernolan],"[christianbale, heathledger, aaroneckhart, mic...",When the menace known as the Joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,"[when, the, menace, known, as, the, joker, wre...","[menace, known, joker, wreaks, havoc, chaos, p..."
3,The Godfather: Part II,"[crime, drama]",[francisfordcoppola],"[alpacino, robertdeniro, robertduvall, dianeke...",The early life and career of Vito Corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,"[the, early, life, and, career, of, vito, corl...","[early, life, career, vito, corleone, new, yor..."
4,12 Angry Men,"[crime, drama]",[sidneylumet],"[henryfonda, leej.cobb, martinbalsam, johnfied...",A jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,"[a, jury, holdout, attempts, to, prevent, a, m...","[jury, holdout, attempts, prevent, miscarriage..."

In [28]:
# Combining all columns into single sentence:

columns = ['Clean_Tokenize', 'Genre', 'actors', 'Director']
sentence_list = []
for i in range(len(df1)):
    words = ''
    for col in columns:
        words += ' '.join(df1[col][i]) + ' '
    sentence_list.append(words)
sentence_list[0]

'two imprisoned men bond number years finding solace eventual redemption acts common decency drama timrobbins morganfreeman bobgunton williamsadler frankdarabont '

In [29]:
df1['Clean_input'] = sentence_list

In [30]:
df1.head()

,Series_Title,Genre,Director,actors,Overview,clean_overview,clean_overview1,clean_overview2,Tokenize,Clean_Tokenize,Clean_input
0,The Shawshank Redemption,[drama],[frankdarabont],"[timrobbins, morganfreeman, bobgunton, william...",Two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,two imprisoned men bond over a number of years...,"[two, imprisoned, men, bond, over, a, number, ...","[two, imprisoned, men, bond, number, years, fi...",two imprisoned men bond number years finding s...
1,The Godfather,"[crime, drama]",[francisfordcoppola],"[marlonbrando, alpacino, jamescaan, dianekeaton]",An organized crime dynasty's aging patriarch t...,an organized crime dynasty's aging patriarch t...,an organized crime dynasty s aging patriarch t...,an organized crime dynasty s aging patriarch t...,"[an, organized, crime, dynasty, s, aging, patr...","[organized, crime, dynasty, aging, patriarch, ...",organized crime dynasty aging patriarch transf...
2,The Dark Knight,"[action, crime, drama]",[christophernolan],"[christianbale, heathledger, aaroneckhart, mic...",When the menace known as the Joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,when the menace known as the joker wreaks havo...,"[when, the, menace, known, as, the, joker, wre...","[menace, known, joker, wreaks, havoc, chaos, p...",menace known joker wreaks havoc chaos people g...
3,The Godfather: Part II,"[crime, drama]",[francisfordcoppola],"[alpacino, robertdeniro, robertduvall, dianeke...",The early life and career of Vito Corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,the early life and career of vito corleone in ...,"[the, early, life, and, career, of, vito, corl...","[early, life, career, vito, corleone, new, yor...",early life career vito corleone new york city ...
4,12 Angry Men,"[crime, drama]",[sidneylumet],"[henryfonda, leej.cobb, martinbalsam, johnfied...",A jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,a jury holdout attempts to prevent a miscarria...,"[a, jury, holdout, attempts, to, prevent, a, m...","[jury, holdout, attempts, prevent, miscarriage...",jury holdout attempts prevent miscarriage just...

In [31]:
df2 = df1[['Series_Title', 'Clean_input']]
df2.head(20)

,Series_Title,Clean_input
0,The Shawshank Redemption,two imprisoned men bond number years finding s...
1,The Godfather,organized crime dynasty aging patriarch transf...
2,The Dark Knight,menace known joker wreaks havoc chaos people g...
3,The Godfather: Part II,early life career vito corleone new york city ...
4,12 Angry Men,jury holdout attempts prevent miscarriage just...
5,The Lord of the Rings: The Return of the King,gandalf aragorn lead world men sauron army dra...
6,Pulp Fiction,lives two mob hitmen boxer gangster wife pair ...
7,Schindler's List,german occupied poland world war industrialist...
8,Inception,thief steals corporate secrets use dream shari...
9,Fight Club,insomniac office worker devil may care soapmak...
10,The Lord of the Rings: The Fellowship of the Ring,meek hobbit shire eight companions set journey...
11,Forrest Gump,presidencies kennedy johnson events vietnam wa...
12,"Il buono, il brutto, il cattivo",bounty hunting scam joins two men uneasy allia...
13,The Lord of the Rings: The Two Towers,frodo sam edge closer mordor help shifty gollu...
14,The Matrix,beautiful stranger leads computer hacker neo f...
15,Goodfellas,story henry hill life mob covering relationshi...
16,Star Wars: Episode V - The Empire Strikes Back,rebels brutally overpowered empire ice planet ...
17,One Flew Over the Cuckoo's Nest,criminal pleads insanity admitted mental insti...
18,Hamilton,real life one america foremost founding father...
19,Gisaengchung,greed class discrimination threaten newly form...

## Feature Extraction

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
tfidf = TfidfVectorizer()
features = tfidf.fit_transform(df2['Clean_input'])
features

<1000x8714 sparse matrix of type '<class 'numpy.float64'>'
	with 21899 stored elements in Compressed Sparse Row format>

In [33]:
features.toarray().shape

(1000, 8714)

## Cosine Similarity:

In [34]:
# Cosine similarity matrix
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(features, features)
print(cosine_sim)

[[1.         0.002639   0.00213424 ... 0.0024737  0.00226522 0.        ]
 [0.002639   1.         0.01867066 ... 0.00259517 0.00237645 0.01603785]
 [0.00213424 0.01867066 1.         ... 0.00209879 0.01864565 0.02246536]
 ...
 [0.0024737  0.00259517 0.00209879 ... 1.         0.03144505 0.        ]
 [0.00226522 0.00237645 0.01864565 ... 0.03144505 1.         0.02900533]
 [0.         0.01603785 0.02246536 ... 0.         0.02900533 1.        ]]

In [35]:
cosine_sim.shape

(1000, 1000)

## Recommendation System

In [36]:
index = pd.Series(df2['Series_Title'])
index.head()

0    The Shawshank Redemption
1               The Godfather
2             The Dark Knight
3      The Godfather: Part II
4                12 Angry Men
Name: Series_Title, dtype: object

In [37]:
pd.Series(cosine_sim[0]).sort_values(ascending = False).head(6)

0      1.000000
505    0.115367
350    0.111517
253    0.080283
179    0.073584
197    0.071722
dtype: float64

In [38]:
list_of_index = pd.Series(cosine_sim[0]).sort_values(ascending = False).head(6).index
list_of_index

Index([0, 505, 350, 253, 179, 197], dtype='int64')

In [39]:
for idx in list_of_index[1:]:
    print(index[idx])

Mystic River
Dev.D
Fa yeung nin wah
The Great Escape
Koe no katachi

In [40]:
movie_idx = index[index == "The Dark Knight"].index[0]
score = pd.Series(cosine_sim[movie_idx]).sort_values(ascending = False)
top5_movie_idx = list(score.iloc[1:6].index)

list_of_recommended_movies = [index[idx] for idx in top5_movie_idx]
list_of_recommended_movies

['Batman Begins',
 'The Dark Knight Rises',
 'The Prestige',
 'Joker',
 'Kill Bill: Vol. 1']

In [41]:
# Resuable function

def recommendation_system(movie_title):
    movie_idx = index[index == movie_title].index[0]
    score = pd.Series(cosine_sim[movie_idx]).sort_values(ascending=False)
    top5_movie_idx = list(score.iloc[1:6].index)
    list_of_recommended_movies = [index[idx] for idx in top5_movie_idx]
    return list_of_recommended_movies

In [42]:
recommendation_system('The Lord of the Rings: The Fellowship of the Ring')

['The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'The Hobbit: An Unexpected Journey',
 'Harry Potter and the Deathly Hallows: Part 2',
 'The Hobbit: The Desolation of Smaug']